### ISSUE TITLE
Opened app and it started resending a picture I had already sent to a room

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1276]
Reported by @vurpo:vurpo.fi
https://github.com/matrix-org/riot-android-rageshakes/issues/235

**Comment by vurpo** [comment]
This has happened a couple of times before, but I don't know how to reproduce it. Usually when it happens, I've shared a picture to a room, then exited the app (home or switch to another app), then later opened the app again using the home screen icon or the app switcher. Sometimes instead of sending the picture again, it instead displays the "share to room" list asking me which room to share to.

**Comment by ylecollen** [comment]
Richvdh got the same issue but i don't see how it is possible.

**Comment by ylecollen** [comment]
Steps to reproduce
1- share a file with Riot
2- open Riot : the rooms chooser is opened. Select a room and go back to the home screen
3- put the application in background
4- kill the application with "Devices monitor"
5 - Resume the application

The ActivityManager saves the HomeActivity state (ie the intent) when it is recreated (because it has been killed).

There is a "share file" extra params which is retrieved and the files chooser is displayed again.
 

https://stackoverflow.com/questions/16837595/will-bundle-savedinstancestate-be-alive-after-application-is-being-killed

**Comment by ylecollen** [comment]
fixed on develop
