### ISSUE TITLE
After installing the fresh app my room/people list didn't sync until I cleared the cache. 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1281]
reported by @tom:lant.uk
https://github.com/matrix-org/riot-android-rageshakes/issues/242

**Comment by ylecollen** [comment]
P2 because we failed to reproduce it.

**Comment by croulibri** [comment]
I faced exactly the same issue.
I installed the new web app in my share hosting server. I connect to it and I can't see any room / direct chat.

If I clear the cache and refresh, then all rooms appear again, but my direct chat (PEOPLE) preference disappeared (I have to set them up as direct chat again) and the low priority room preference also (have to drag them again.
The mess up is then sync to the server because the organisation of my room as direct chat / low priority rooms disappear when I connect back to the old version of Riot Web.

**Comment by ylecollen** [comment]
duplicate of https://github.com/vector-im/riot-android/issues/1302
