### ISSUE TITLE
Read marker doesnt move when scrolling down in a room. it stucks below an event and above an image

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1365]
Reported by @jeangb 
https://github.com/matrix-org/riot-android-rageshakes/issues/425

**Comment by jeangb** [comment]
How to reproduce:

1. Being in preview mode, after hit the "Jump to last unread marker" banner
2. Scroll down in order to have an image being the last unread event
3. Quit preview mode, then hit "Jump to last unread marker" banner

The last unread image won't be centered as expected, and there'll be no unread marker.
I connected with the same account on riot-web, the unread marker was placed at the expected unread image.
I think this issue is more likely to be reproductible when the events are mostly images.

**Comment by sabrinaj** [comment]
- > The last unread image won't be centered as expected, and there'll be no unread marker.

 This should now be fixed. It was because we were centering on the last read and not the first unread and since the read marker is displayed at the bottom of the last read, it was hidden if the bottom of the last read was out of screen.

- Couldn't reproduce the read marker being stuck.

**Comment by jeangb** [comment]
Validated.
