### ISSUE TITLE
Phone went to sleep while uploading a photo. Now it cannot send the photo.

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1390]
Reported by **nevs**.

https://github.com/matrix-org/riot-android-rageshakes/issues/451

**Comment by sabrinaj** [comment]
Couldn't reproduced.

**Comment by ylecollen** [comment]
This is a race condition : the images are uploaded in two steps
-> the thumbnails are uploaded first : the url is a file one. It is updated with an URL provided by the server when the upload succeeds. The source file is deleted.
-> the high-res pictures are upload after the thumbnails  with the same trick than the thumbnails.

The image event was not flushed between the two steps so if the application was killed between the two steps, the file URL was become invalid because it did not pointed to the right file.
