### ISSUE TITLE
improve the code display (double and triple backticks)

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#145]
from android chat

it would be nice if single and tripple backtick blocks (ie: code blocks) had a different background color,
and tripple backtick blocks didn't get wrapped, instead had a scrollbar as they do in vector web

Morever, the webclient formats the code blocks with another way than backticks.
I assume it is the third case ie the formatted code text should also be displayed with another background.

**Comment by kebertx** [comment]
Code is formatted really badly in the android client. Sharing code in a matrix chat room is a really common use case for me, but reading a code block in the mobile client is actually a huge pain.

The least code blocks should do is preserve indentation, but the app pushes each line to the left margin:

![screenshot with code block](http://i.imgur.com/3Hb4hgh.png)

The right margin is also visibly different on each line, which is ugly and sort of misleading – it looks like each line is a separate statement instead of part of a single block. And, like @ylecollen mentioned, if a line is too long (which on a phone is more often than not) it wraps around to the next line.

It just needs to be done better. In general, it should be able to present code just as well as the web client. With syntax highlighting, spacing, and no line wrapping!

**Comment by kebertx** [comment]
Just a friendly semiannual reminder that the android client still displays code [like this](http://i.imgur.com/aKTWAjf.png).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x09ac791666530f893db59be0815fe7c24f2dee2d5faae2727a076a976c6c0a6c](https://etherscan.io/tx/0x09ac791666530f893db59be0815fe7c24f2dee2d5faae2727a076a976c6c0a6c)
