### ISSUE TITLE
Add a way to limit the used application storage

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1456]
Riot keeps the downloaded medias without deleting them.

We need to have a slider or so to let the user defines a max cache size.

**Comment by Mikaela** [comment]
I see Riot taking ~1 GiB around the time this issue was created.

![riot](https://teleirc.mikaela.info/77bo0PVD/file_97.jpg)

In case the issue is caused by cached media files, I think another option would be having an option to configure how long media is cached like Telegram does, screenshot below is the option in Telegram opened.

![telegram](https://teleirc.mikaela.info/0CS4omZ6/file_98.jpg)
