### ISSUE TITLE
Better icon for speaker toggle

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#1587]
The current icon isn't very clear on what it does exactly (looks like WiFi combined with a phone):

![screenshot_20170910-173901](https://user-images.githubusercontent.com/1342360/30254804-5d9f784a-9652-11e7-940d-b7c0e248fe25.png)

Something much more people recognize is the loudspeaker icon:

![wear speaker android wear app](https://user-images.githubusercontent.com/1342360/30254807-75bb6f6a-9652-11e7-8b5b-12f1f9c06405.png)

Changing to this icon type would help clear up confusion.

**Comment by ylecollen** [comment]
We followed the design requirements

**Comment by anoadragon453** [comment]
Oh yeah, definitely not saying it's bad! Just created the issue since a user said they were confused by the current icon, and I agree that the other one is more universal.

Feel free to go with whatever design specifies instead :)

**Comment by haadr** [comment]
I agree. Not wanting to knock anyone's work, I haven't met anyone yet who's immediately understood what it means except by elimination (ie. there's no other icon that could mean "speaker", so this has to be it).

Only commenting because I want Riot to have "mainstream appeal", and this is part of it.

**Comment by ylecollen** [comment]
The speaker icon is the material design one
see https://material.io/icons/ in call section
