### ISSUE TITLE
[E2E Encryption] Cannot start calls in E2E rooms

### ISSUE THREAD

**Issue by clxcoltz** [vector-im/riot-android#1674]
I realize E2E encryption is still very much in development, but I figure I'd drop this to call attention. Messaging in E2E works fine, but calling just fails (tested: Android 0.7.03 <-> iOS); when picking up it will get to "call connecting..." before failing. Calls in regular rooms work, but I love the E2E rooms so I wish it can move along to at least a testable state.

**Comment by dva-re** [comment]
https://github.com/vector-im/riot-web/issues/2669

We tested this.
In fact, as far as I understand, the problem is in the version of iOS client, and only in encrypted rooms and only when you need TURN. If both clients are connected to the same router or one VPN network, then the connection works successfully.

**Comment by ylecollen** [comment]
IOS issue
