### ISSUE TITLE
After a user redacted their own join event from HQ, Android DoSes us with /context requests

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1859]
We saw 2061 requests to '/_matrix/client/r0/rooms/%21cURbafjkfsMDVwdRDQ%3Amatrix.org/context/%2415153218301304484Fpgds%3Amatrix.org?limit=1' from Riot/Android clients after a user redacted that event (they sent 3 redactions, as presumably it didn't seem to work).  This looks to have contributed to taking out the main synapse process for ~30 minutes

**Comment by ara4n** [comment]
![screen shot 2018-01-07 at 12 11 33](https://user-images.githubusercontent.com/1294269/34649302-69d42002-f3a4-11e7-8c15-c98805b5c954.png)

^ the carnage this caused on CPU on the context servlet

**Comment by ylecollen** [comment]
The main problem is the performance of room state events redaction
-> either the client lets the server does the job : it looks weird that only 2061 requests are enough to stuck the server for 30 minutes
-> or the android stores the state events. It means to save about 13000 state events for Matrix HQ, load them in redaction case and recompute the new room state status.
On low / middle range devices, the storage explodes + many devices already reported that the application crashed because of it.

**Comment by ara4n** [comment]
why is it calling /context at all, though? the right API to recompute the state is /state (which may be less heavy)?

**Comment by ylecollen** [comment]
@ara4n 

When an event is redacted (from the sync)

-> check if the event is known, if it is a room state, compute the new room state from the state events list stored in the application store (disabled on Android because of out of memory crashes)

-> if the event is not known, a "getContent of event" request is triggered to retrieve the message type. If a room state event, we perform a room initial sync.

**Comment by richvdh** [comment]
(the agreed solution is to implement /rooms/{roomId}/event/{eventId} on the server and have the mobile client use that instead of the more heavy-weight .../context/...)

**Comment by ylecollen** [comment]
@richvdh @ara4n 
getContextOfEvent is replaced by getEvent which
1- tries  /rooms/{roomId}/event/{eventId}
2- if the new request is not supported, tries /events/{eventId} (which still works)
3- if "/events/{eventId} " is not supported, use the /context request
