### ISSUE TITLE
IRC Bridge to Freenode having issues, messages are constantly out of order, and some people's messages just haven't been coming through at all

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#2025]
reported by @ctmartin:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2057

**Comment by ArchangeGabriel** [comment]
Well this is likely an matrix-appservice-irc bug, right? Or maybe just in its matrix.org configuration because I have no issue on my own deployment. On channel bridged by matrix.org I’ve noticed the two following things:
– user joining the channel (IRC side) and posting right away don’t get their messages synced, until they get joined in Matrix which usually happens several minutes later.
– PMs started toward me by IRC users are also only synced a while after, and are empty when joined.

**Comment by ara4n** [comment]
this is almost certainly due to the same overloaded matrix.org homeserver problems which have been extensively discussed in #irc:matrix.org over the last few weeks. hopefully they will be mitigated with forthcoming perf improvements there.
