### ISSUE TITLE
Privacy: Riot should never pass events content to GCM

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2051]
at least without the clear consent from the end user.

When the [background sync](https://github.com/vector-im/riot-android/blob/e0e703d09a8b330d2779e75485c0ad0181d7452a/docs/notifications.md#background-sync-disabled) setting is disabled, Riot asks Sygnal to send matrix events content to GCM so that Riot can directly display detailed notifications from the GCM notification payload.

This is efficient for the battery and the network usage but this is a privacy concern. 
This is even a privacy issue because the app does not inform end users about that (see #2044) and what is behind this setting.

There are 2 approaches to fix this:
- never send content to GCM
When the setting is disabled, the app must not ask Sygnal to send event content to GCM. The user will see less detailed notifications like `X new messages in RoomY`.
- add another setting when *background sync* is disabled: `"Keep full detailed notifications"` with a subtitle `"This requires to send non encrypted message content through Google services servers"`.

**Comment by ylecollen** [comment]
@manuroe 
1- "Riot should never pass events content to GCM"  seems wrong : Riot should never request the event contents when background sync is disabled

2 - it might also be fixed server side : many HS owners updated the GCM management to keep only the eventID/RoomId/nbr of notified rooms

3- to be sure that your privacy is kept, you should never used unencrypted rooms. Else the HS administrators could dispatch what you said.
The GCM payload does not have the message body if the room is encrypted.

4- as Master Coffee said, Riot will need to have an "advanced settings" or so. 

**Disable background sync** was implemented to save battery because the sync responses were too verbosed with presence.
By now, it seems that many users would prefer having a **stop notifying me** feature.

An endless story

**Comment by manuroe** [comment]
> 1- "Riot should never pass events content to GCM" seems wrong : Riot should never request the event contents when background sync is disabled

@ylecollen, could you please elaborate?
I cannot see what is the problem with the title. I (well, we ;)) fail to see the difference between these 2 sentences.
The isue we want to solve here is to avoid do send messages contents to GCM, at least without informing the user. 
Like in e2e messages, sending clear message metadata is fine, ie we do not need to inform the user.
But we need to warm them when an application setting make their messages contents go to GCM.

> 2 - it might also be fixed server side

I agree. HS can enforce this. But this is the role of the app to inform the user what it is sent to third parties like GCM.

> 3- to be sure that your privacy is kept, you should never used unencrypted rooms

True. But the issue here is to improve the behaviour regarding non e2e rooms.

> 4- as Master Coffee said, Riot will need to have an "advanced settings" or so.

Yes, it looks like that we will end with another settings as suggested in the 2nd proposed solution to please everybody. 
Thanks a lot for sharing the feedbacks you got from end users like Erik's one.

> An endless story...

We might not be able to make everybody happy. But this is going better and better. ATM, GooglePlay users just want more information about what's behind settings. This is not a big thing regarding all you have made.

**Comment by ylecollen** [comment]
@manuroe 

1- 
"Riot should never request the event contents when background sync is disabled" : the issue is only triggered in this case.

If an user searches if his issue has been fixed, i'm not sure he will make the relationship with "Privacy: Riot should never pass events content to GCM"
 
From developper POV, it's the same.

NB : The fix is quite simple -> a boolean to set to false.

2- _But we need to warm them when an application setting make their messages contents go to GCM_.
No other Google play applications tell what they put in the GCM payload...

Riot becomes a too geeky product day after day 

3-  Should it be removed server side ?
For a secured chat application, it should be removed.
