### ISSUE TITLE
Reply should show 'normal pill' instead of mxid

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#2468]
Riot-Web creates pills which contains the displayname of the user as pill content. Somehow the replies created on android contain the mxid (which confuses me)

**Comment by lnxwalt** [comment]
Just a quick comment. When fixing this, don't completely hide the MXID. Many people change their displaynames frequently, so it needs something stable being part of the representation. Yes, choosing username:servername instead of the much more familiar username@servername _is_ confusing to most people, but that's a different issue.

Maybe `Displayname (MXID)` would work best.

**Comment by lixmal** [comment]
> Just a quick comment. When fixing this, don't completely hide the MXID. Many people change their displaynames frequently, so it needs something stable being part of the representation. Yes, choosing username:servername instead of the much more familiar username@servername _is_ confusing to most people, but that's a different issue.
> 
> Maybe `Displayname (MXID)` would work best.

I guess you could always tap on the name to see full details including the mxid?
Riot-Web shows the display name only and I think it should be consistent across all clients (no idea about iOS right now, though).

**Comment by lnxwalt** [comment]
It should be consistent across same-named clients (e.g., Riot-Web, Riot-Android, Riot-iOS), yes. That means they should all do this.

Tapping takes you to a different page.
