### ISSUE TITLE
Messages get sent twice

### ISSUE THREAD

**Issue by f0x52** [vector-im/riot-android#2485]
I've been having this problem for a while now, on latest riot-android from f-droid. Some of my messages (maybe 10% of the time?) get sent twice after pressing send (once). This is especially annoying in irc rooms since redacts are useless there.

**Comment by bmarty** [comment]
Hello @f0x52 ,

Thanks for reporting this issue. https://github.com/matrix-org/matrix-android-sdk/pull/323 should fix this issue. This fix will be available in the next release, schedule for this week (probably next week for f-droid). Please shout if the issue is still present on version 0.8.13.

Benoît
