### ISSUE TITLE
trying to share a picture from Riot to WHatsApp fails with file format not supported

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-android#2530]
steps: long press on a photo in Riot, select share, select WhatsApp -> whatsapp opens and shows the error 'format not supported'. Probably a problem on WA side who is limiting the file format but maybe we do sthg unexpected on our side?

**Comment by bmarty** [comment]
Ok, thanks for reporting, I can reproduce the issue, by sharing with WhatsApp, with GMail, with anything actually.
I'm investigating

**Comment by bmarty** [comment]
The decrypted media is deleted during the time you select an application to share with, because the application is going to background. If you're fast enough (< 4 s) to select the application and do other(s) step(s) before this third party application request the media (ex: select a group in WhatsApp), it works well.

I'm wondering how to fix this issue properly.
