### ISSUE TITLE
Unable to click links in m.emote messages

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2669]
After the recent fix to markdown `m.emote`s, I'm not unable to click any links in `m.emote` messages.

Latest F-droid build, 0.8.18

**Comment by bmarty** [comment]
Confirmed, @BillCarsonFr can you check please?

**Comment by BillCarsonFr** [comment]
I have been able to reproduce, it is related to #2891
It happens when the markdown (formatted_body) contains a link that is not found by text auto link.
Autolink should not be called on formatted body, because autolink always removes existing URLSpan before trying to detect by himself. So if the markdown link has no protocol the autolink behavior is to be strict on the domain name (only accept known domain -iana-), meaning that for non iana domain the original URLSpan is removed, and nothing is added by autolink.
The following message will not be clickable:
```
{
    "body": "Status: **_success_**<br/> Build: [ansible/xoxys.matrix#2c0b65eb](https://server.com/ansible/xoxys.matrix/34) (master) by xoxys",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>Status: <strong><em>success</em></strong><br/> Build: <a href=\"https://drone.rknet.org/ansible/xoxys.matrix/34\" rel=\"nofollow\">ansible/xoxys.matrix#2c0b65eb</a> (master) by xoxys</p>\n",
    "msgtype": "m.notice"
  }
```
