### ISSUE TITLE
Bug report share options is too generic

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-android#274]
When I want to send a bug report I get the option of sending it via email, vector, dropbox, blah, etc etc. is it possible to restrict this to email clients?

**Comment by ylecollen** [comment]
The android fragmentation does not help us.

1- we use intent.ACTION_SEND_MULTIPLE action because SEND or SENDTO don't seem to support email attachments.
It also depends if the user has installed some clients which might support it.
SEND_MULTIPLE seems supported by all the android devices.

2- i tried to display the email clients first
                __// list the intent which supports email
                // it should avoid having lot of unexpected applications (like bluetooth...)
                Intent emailIntent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts("mailto", "example@gmail.com", null));
                emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Mail subject");
                List<ResolveInfo> resolveInfos =    mContext.getPackageManager().queryIntentActivities(emailIntent, 0);
                final List<LabeledIntent> intents = new ArrayList<>();
                for (ResolveInfo info : resolveInfos) {
           
                    Intent intent = new Intent(Intent.ACTION_SEND_MULTIPLE);
                    info.loadLabel(mContext.getPackageManager()), info.icon));
                }
                Intent chooser = Intent.createChooser(intents.get(intents.size() - 1), "...");
                chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS, intents.toArray(new Parcelable[]{}));
                mContext.startActivity(chooser);__
It seems working on a nexus 6 (android 5.1), but EXTRA_INITIAL_INTENTS is ignored on a Samsung S5.
  EXTRA_INITIAL_INTENTS seems also buggy on Android 6

**Comment by bmarty** [comment]
BugReport are now done with a dedicated screen. I close the issue
