### ISSUE TITLE
Tray icon is gone in Fdroid, there is regular syncronizing notification instead

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-android#3103]
Hi
 
I am using Fdroid 0.8.28 on LIneage OS 14.1

There used to be a  notification tray for Riot always now. That notification is now gone. It was there  in 0.8.26

Not just that but now I see "Syncronizing" instead constantly every x seconds, and that is really distracting to see in the tray as if something is going on and I feel  like I need to check it, because that kind of similar "cycle" icon is used by many applications.

Can you please bring tray notification back and remove the syncronizing notification from the tray for the Fdroid builds? It should syncronize in the background without any notification thing in the tray.

thanks

**Comment by lhucinequr** [comment]
I have lost the tray notification since the last update (0.8.28 f-droid)

**Comment by bmarty** [comment]
Due to Android background limitation, on order to save device battery and to force application to be transparent to the user, it's not possible to synchronize in the background without displaying a notification. Asking for ignoring battery optimization is bad practice.

**Comment by gerroon** [comment]
Personally, I am perfectly fine with the previous setup where we had a permanent notification. I never had real issues with Riot battery usage in that way.

**Comment by gradinaruvasile** [comment]
Same here. Also the sync notification stucks there sometimes. On server side i see connections every 2 or si minutes instead of the 20 seconds i set.

**Comment by vsatmydynipnet** [comment]
Sync is definitely a problem since 0.8.28. It may be good practice how is is done now, but it has destroyed a perfectly working notification, incoming call alerting and furthermore actually there is most of the time the R in the status, which looks like there is a message, then, when opening its this new sync thing.

Please make it switchable:
- old version, which worked perfect, never had battery problems for people need working notifications
- new version, for people thinking this helps them with their battery and it is enough to see messages after unlocking the phone

In the night it simply does not notify my till the morning.

IMHO a better filled battery doesn't help, if things are not working reliable, which was till 0.8.28. 

Thank you for your hard work.

**Comment by gerroon** [comment]
I also started getting notifications for "X answered call" when I call X. I naturally know the X answered since I am talkign to X. That is a bit useless.

**Comment by bmarty** [comment]
Replaced by #3122
