### ISSUE TITLE
Is new app in Google play store a fake/malicious or legit?

### ISSUE THREAD

**Issue by ymudryy** [vector-im/riot-android#3137]
Today I when opening Riot.im on my Android device I saw a message that as a security measure a new Riot.im app must be installed. Also the app is now called "Old Riot.im" (updated as of April 23rd).

Things that look suspicious are:
1) In Releases (https://github.com/vector-im/riot-android/releases) the latest version is v0.8.29, but in Play Store the version is 0.9.00.
2) The link that explains why new app must be installed is: https://medium.com/@RiotChat/riot-im-android-security-update-2b3f655ad739 (why it's on medium.com domain?)
3) I cannot find any other details when googling for Riot.im version 0.9.00, nor I can see any other  mentions about this security measure to reinstall new version of the app on the main GitHub page for riot-android.

Can someone please clarify?

p.s.: I know this is not a technical issue, but I didn't know where else to post to get fast attention in case this is a hack of Vector's Google Play account and someone is trying to get people to install malware app.

**Comment by bmarty** [comment]
The new application (https://play.google.com/store/apps/details?id=im.vector.app) is legit and comes from New Vector team, but is not currently available.
It has been removed from the Play Store for violating the User Generated Content (UGC) policy (see https://twitter.com/RiotChat/status/1121414206530699264).
We're working on putting it back online.

About your points:

1- The commits has not been pushed yet because of a security fix we do not want to reveal before everyone is up to date.
2- medium.com is used to host the Riot blog. A twit on Twitter from @ RiotChat link to it (https://twitter.com/RiotChat/status/1120758476312064002) (and the Twitter account has not been compromised AFAIK)
3- See point 1

We understand that you can be suspicious, it's quite legitimate. I assume that if all was wrong and fake, then you'll heard something about it by a way or another.

We are very sorry for the inconvenience

Benoit

**Comment by ymudryy** [comment]
Thank you for explanation!

I will close this issue now.
