### ISSUE TITLE
Calls "Media Connection Failed"

### ISSUE THREAD

**Issue by kernitus** [vector-im/riot-android#3321]
Since a few weeks ago, when I try to make or receive a voice or video call on Riot Android it gets stuck on `Call connecting...` and then says `Media Connection Failed`. I have tried logging out/in, clearing app cache and even reinstalling the app itself. Calls work on laptop using the same account.

I have used the in-app `Report bug` feature calling it _Calls fail with "Media Connection Failed"_ but I'm not sure where that goes or if it is publicly accessible.

**Comment by jasmir** [comment]
Same problem here. One device shows "Media connection failed" on every attempt to initiate a call. Interesting points:
- tcpdump on the gateway shows, device is not even trying to connect to the turn-server
- logs on turn-server shows no signs on contacts from the affected device
- only one device is affected. The other devices on this synapse-servers and even the same account on the desktop client has no problems

I send a Bug Report from this device with logs, also.

**Comment by huguesdk** [comment]
i have the same problem. it was working fine previously. i think it stopped working when the fallback to google’s stun servers was removed.

i’m trying to make calls between two different homeservers, each configured without a turn server (because behind nat routers with a dynamic i.p. and no nat loopback). on both riots the option to fall back to turn.matrix.org is active.

note that it mainly affects riot android. with riot web, it works most of the time.

is there a recommended way of configuring synapse without an own turn server while allowing clients to make and receive calls successfully?
