### ISSUE TITLE
Firefox account SSO doesn’t work

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#3337]
Apparently signing in with FxA on Riot and RiotX still fails with: 
"Cookies and local storage are required"

**Comment by 532910** [comment]
I don't see such option at all.

**Comment by justdave** [comment]
> I don't see such option at all.

If you pick "Single-sign on" (sic) as the login method, Firefox Account is one of the options given on the Auth0 screen that it takes you to (if you weren't already logged into Auth0).

It still fails with the above-mentioned cookie error if I try it though.

**Comment by justdave** [comment]
This is specifically with mozilla.modular.im as the server, fwiw

**Comment by laghee** [comment]
If I'm understanding this correctly, this looks to be solvable either by using the user's default browser rather than a webview here:
https://github.com/vector-im/riot-android/blob/f3b8c4c6c89a6660611acaa127d96af1e1261d72/vector/src/main/java/im/vector/activity/VectorWebViewActivity.kt#L35

**Or** by finding a way to support OAuth without local storage on the mozilla/fxa side, [where there's an (old-ish) existing issue](https://github.com/mozilla/fxa/issues/641).

While there are workarounds (e.g., using GitHub with 2FA), this is a fairly annoying problem for those of us who use their FF account to auth in. Since I logged onto the new matrix modular server with Firefox auth originally, I can't have the same user name on android using GitHub auth (which also seems to mean I can't access any of the same private rooms I'm in on the desktop/web app).

Someone at a higher pay grade might know who would be the appropriate person to ping to prioritize here?

**Comment by MattWThomas** [comment]
Can we add an option (or default behavior) to allow the use of the default browser instead of the webview as mentioned above. It seems like the simplest solution, and will help other companies down the line who want to use SSO.

**Comment by bmarty** [comment]
Fix in release 0.9.10
