### ISSUE TITLE
Android app can't customize identity server on login page

### ISSUE THREAD

**Issue by f4nff** [vector-im/riot-android#3358]
Android app can't customize identity server on login page

There is no such problem in ios!

**Comment by BillCarsonFr** [comment]
There has been a recent update in synapse related to privacy https://github.com/matrix-org/synapse/releases/tag/v1.4.0 (https://medium.com/@RiotChat/new-privacy-controls-for-riot-dc3661888563)

Updated homeservers may not require an identity server in order to register emails or phone numbers (there is flag for that, if identity server is not needed by the homeserver you will not see the option to set it)
iOS update is not yet live, after the update it will be the same.

You now have a 'disovery screen' in the settings where you can choose an identity server and decide to share or not email/msisdn.
