### ISSUE TITLE
Client unable to send messages

### ISSUE THREAD

**Issue by D3XX3R** [vector-im/riot-android#3372]
Since the last update of Matrix-Synapse I'm unable to send messages with my Android Client.

When I write a message and send it, the message turns green.
After some waiting it just says that it couldn't send my message and asks me if I want to retry it,
or if I want to cancel it.

**Comment by rbns** [comment]
We've experienced this problem too, with synapse 1.5.1 and only with encrypted rooms. Clearing the app data and cache (to force a resync) fixed it for me.

**Comment by florian2833z** [comment]
Is this going to get fixed? It's very annoying.

**Comment by tobiasd** [comment]
Cleaning only the cache of riot was enough here. Thanks @rbns

**Comment by ivilata** [comment]
I've also been bitten by this and it is really annoying, especially for non-technical users who just see it as "Riot is not working" and even more especially because since it's triggered in encrypted rooms, it directly affects non-casual use of the system.

I tried on several devices to just clean the cache (not app data), but it didn't do the trick for me. :cry: 

Would it be safe to temporarily revert to say Matrix Synapse 1.4.1? I also see that 1.6.0 is out, I'll try it and report back…

**Comment by ivilata** [comment]
Upgrading to Synapse 1.6.0 seemed to fix the issue (for the moment) and all pending "grey and green" messages went through. I don't know which one of the fixes in the release did the magic, though!

**Comment by florian2833z** [comment]
> Would it be safe to temporarily revert to say Matrix Synapse 1.4.1? I also see that 1.6.0 is out, I'll try it and report back…
I'd say you just relogon to your mobile devices, that fixed it for me.

**Comment by D3XX3R** [comment]
This is a bit old. Don't know if fixed or now.
Possible walkarounds are to clear the cache of the app or to logout and log back in.
Both ways need you to login again anyways.

// closed
