### ISSUE TITLE
Cannot sign in on home server -invalid password

### ISSUE THREAD

**Issue by DJJ88** [vector-im/riot-android#3410]
I'm using the latest version of Riot on f-droid.  When I try do login using a home server different from https://matrix.org, I get invalid login/password. It's suprising because i can connect using the same login and password on the web app https://riot.im/app/#/welcome.

**Comment by devnapper** [comment]
Are you still experiencing this issue?
Looks like I possibly ran into the same one. I tried to login from Riot in Android with my full username (@[myname]:[myserver]) and it failed due to a wrong password. But the password was definitely correct and worked just fine on Riot Desktop/Web.
By taking a look into my homeserver's log file, I found the same error message alongside with the user name as in the form above.
Then I figured out that I have to put just my username without the server part into the username field within the app, ignoring the overall syntax. By adding the server's URL explicitly under server options, another login attempt was successful then.

**Comment by eugenetaranov** [comment]
hello, I hit the same issue. Android 10, Riot.im updated on May 20, 2020. It says invalid username/password but the same login/password/server worked fine in the browser and desktop application. Please let me know if additional information is required.
P.S. I have used just username, server was specified in the dedicated field.

**Comment by jmillerv** [comment]
Just wanted to bump this as I'm having the same issue. Reset my password through my active session just in case but still can't login. I'm also on Android 10.

**Comment by jmillerv** [comment]
> hello, I hit the same issue. Android 10, Riot.im updated on May 20, 2020. It says invalid username/password but the same login/password/server worked fine in the browser and desktop application. Please let me know if additional information is required.
> P.S. I have used just username, server was specified in the dedicated field.

I found the RiotX client. You may have solved this issue for yourself but I was able to get logged into my personal server through that on my phone. 

https://f-droid.org/packages/im.vector.riotx/
https://play.google.com/store/apps/details?id=im.vector.riotx
