### ISSUE TITLE
Add Notification Panel 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#553]
linked to IOS issue
https://github.com/vector-im/vector-ios/issues/616

**Comment by giomfo** [comment]
@antikewl

**Comment by antikewl** [comment]
The behaviour is a little different to the iOS due to common UI differences between the platforms, but the intention is the same. 

Same question as my comment in vector-im/vector-ios#616 -- Should this new screen include the same contents as the right notifications panel on the web app? If so, I'll add it in.

Notifications option on menu: https://zpl.io/Z25f89B
Menu with new notifications: https://zpl.io/niY3V
New notifications indicator on Messages screen: https://zpl.io/13gzOW

**Comment by giomfo** [comment]
LGTM

**Comment by bmarty** [comment]
Seems done
