### ISSUE TITLE
DNS resolution and SRV

### ISSUE THREAD

**Issue by blacoste** [vector-im/riot-android#727]
When trying to validate the form to log in using an alternate Matrix server, the application requires the user to specify the TCP port instead of using the _matrix._tcp.domain SRV record.

**Comment by ylecollen** [comment]
Could you create us a dummy account on your home server ?

**Comment by bastoon06** [comment]
Credentials sent at android a@t riot.im.

Use advanced form to log in. User is forced to enter port 8448 on Matrix server.

**Comment by Matrixcoffee** [comment]
The SRV record is for other federated servers, and making clients look up the SRV record is not the correct behaviour here.

The client host and port can be entirely different from the federation endpoint. e.g. servers talk to example.com:8448 and clients connect to matrix.example.com:443.

**Comment by madduck** [comment]
I think this even goes a step further. When I try to log in to Riot-Android (F-Droid version here), I am asked for my "email  address or username". There's an option to specify custom server options, but it's labelled advanced and I should not need to touch it.

However, when I try to log in as `madduck@madduck.net` with the correct password, I am told the password is wrong. This is probably because Riot tries to log me in to the default `matrix.org` homeserver with the username `madduck@madduck.net`, when in fact I expect it to do a `SRV` lookup on the domain to figure out the homeserver:

    % dig +short SRV _matrix._tcp.madduck.net
    0 0 8448 matrix.madduck.net.

I also tried `@madduck:madduck.net`, but that also fails.

If I enter `https://matrix.madduck.net:8448/` manually into the advanced server field and change the username to just `madduck`, then login works. But this is not what users expect, especially not those who don't want to be confronted with "advanced" settings.

**Comment by Matrixcoffee** [comment]
The SRV record is intended for federation (other servers). The client endpoint and federation endpoint can be on entirely different hosts and ports, and there currently isn't a way to automatically look up the client endpoint. There needs to be a solution for this, but looking up the SRV record is not that solution.

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-doc/issues/433 is the embarrassingly wedged bug for this.

**Comment by blacoste** [comment]
So thanks to ara4n comment it seems to be a Matrix specification pending issue.

madduck, you should submit a bug issue with your comment. This is a real issue that the user cannot simply use an alternate server in a simple way.

At the moment I close this issue as it is not app relates.

Thanks for your comments.
