### ISSUE TITLE
sss's crypto is broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#797]
> Crypto is freaking out . It's broken
First it kept saying crypto isn't enabled and after a restart now it saying it didn't receive they keys
Running Android 7.1.1
Used to work just fine

logs at: https://matrix.org/_matrix/media/v1/download/matrix.org/hBizdYrNmemeyNBqQutXaHyW

**Comment by ylecollen** [comment]
i never tested on an android 7.X device.

Could i have more details ? how was it triggered ? after an application update ?

**Comment by ylecollen** [comment]
@sss:matrix.org
10:01
OK what first happened is that I went to my old e2e enabled room and it said I couldn't read my messeges because e2e wasn't enabled . I checked the room settings and it showed that e2e was enabled . I restarted the app and it was fixed . But crypto was still odd in other rooms new messeges would either have key not sent error or it would work normally
Options
I had vector/riot installed a long time ago maybe many months of it in the background accumulated junk

**Comment by ylecollen** [comment]
Should be fixed with the latest version.
