### ISSUE TITLE
Voice calls (even unsuccessful ones) break bluetooth media headsets

### ISSUE THREAD

**Issue by pganssle** [vector-im/riot-android#919]
Using an LG V10 with a bluetooth headset and the F-droid version of Riot Android, I tried doing a voice/video call. Even dialing and not having the other person pick up caused my bluetooth headset to stop working as a headset - I can still use the headset controls to navigate my audio, but the audio just plays out of the phone's speakers.

I had this exact same issue several months back (maybe 4-5?), so it seems it's been in there for a while.

Disconnecting and reconnecting the bluetooth doesn't do anything. Restarting Riot does not do anything. The only thing that fixes the bluetooth headset as far as I can tell is restarting the phone.

**Comment by ylecollen** [comment]
Sorry, we did not have time yet to investigate it.

If you have time to help us, you are welcome.

**Comment by helmo** [comment]
I had a similar problem .... no riot sound over my headset.
Connecting a cable to my bluetooth headset worked but defeats the purpose of having a bluetooth headset ;)

**Comment by inducer** [comment]
I think the problem here is a bit more general than what the title suggests. While running and after any type of voice/video call (even if unsucessful), Android's audio routing is out of whack until you force-quit Riot (drag to "Info" from the app drawer), after which it returns to normal.

Steps to reproduce (e.g.):

1. Be connected to Bluetooth speakers
1. Attempt voice call, hang up before connection established
1. Play music, note that music comes out of "phone earpiece"
1. Force quit (and possibly restart) Riot
1. Audio routing returns to normal

The saving grace here is the force-quit workaround.

**Comment by dva-re** [comment]
Problem still there. But in my case the solution is swipe from the list of recently used apps.
